usdot-fhwa-stol/carma-web-ui

website/Dockerfile, website/docker-compose.yml, website/index.html, website/logout.html, website/main.html, website/scripts/control.js, website/scripts/docker_kill.bash, website/scripts/docker_launch.bash, website/scripts/googlemap.js, website/scripts/kill.bash, website/scripts/launch.bash, website/scripts/launchPlatform.php, website/scripts/rosbridge.js, website/styles/styles.css
Updated copyright notice on all source files to reflect 2019 (CAR-214)
=> Copyright updated.

website/scripts/docker_kill.bash, website/scripts/docker_launch.bash
Counterpart to CARMAPlatform#185 to ensure clean system shutdown
=> Add project flags to docker-compose commands

website/images/vehicle_lightbar.svg, website/lanesample.html, website/main.html, website/scripts/rosbridge.js
Changes are:
- Added the lightbar to UI  (Related to JIRA CAR2-161 task)
- Removed some unused code and comments. 
Tested these changes on the local development environment.
=> Added lightbar to UI

.circleci/config.yml
Add support for code coverage metrics to sonar cloud
=> Add support for code coverage metrics to sonar cloud

docs/pull_request_template.md
PR to add PR template to CARMAWebUi
=> adding pr template

Dockerfile, docker/build-image.sh, docker/get-component-version.sh, docker/get-image-name.sh, docker/get-repo-name.sh, docker/get-system-version.sh, docker/install.sh, website/index.html, website/logout.html, website/main.html, website/scripts/control.js, website/scripts/docker_kill.bash, website/scripts/docker_launch.bash, website/scripts/googlemap.js, website/scripts/kill.bash, website/scripts/launch.bash, website/scripts/launchPlatform.php, website/scripts/rosbridge.js, website/styles/styles.css
PR to add updated copyright info to the dev branch.
[CAR-1532](https://usdot-carma.atlassian.net/projects/CAR/issues/CAR-1532?filter=allopenissues&orderby=priority%20DESC)
Required to keep our licensing up to date with the new year
Tested by building image. See below screenshot:
=> Updated copyright info

docker/build-image.sh
PR adds test option to build-image.sh script. This will allow devs to easily build images tagged for our test repo in line with the new integration testing workflow.
Image was build using build-image.sh and verified that it was tagged under the correct name.
=> added test option to build-image.sh

website/main.html, website/scripts/control.js, website/scripts/googlemap.js, website/scripts/rosbridge.js, website/widgets/autoware/widget.js, website/widgets/cruising/widget.js, website/widgets/traffic_signal/widget.js
Fix the integration routing merge override issues
Seven JS files are modified based on the pull request #36 .
Compared to pull request #36 , Make sure all the changes in the #36 stay.
https://github.com/usdot-fhwa-stol/carma-web-ui/pull/36
Merged develop branch code into integration routing code. The changes are not reviewed properly and override some old changes that should stay. This pull request is to re-apply the old changes for integration routing to the  latest version of integration routing. 
It will resolve the lost changes made.
Run a ./buld script to make sure building process work after all the changes.
=> fixbugs: integration/routing override issues

install_scripts/Desktop/CARMA_UI.desktop, install_scripts/carma_web_ui_setup.bash, website/scripts/3D/renderers/renderer.js, website/scripts/app/global_variables.js, website/scripts/app/subscribeROSServicesOnLoad.js, website/scripts/ros/ros_comms_inbound_outbound_binary.js, website/scripts/ros/ros_drivers_state.js, website/scripts/ros/ros_guidance.js, website/scripts/ros/ros_host_vehicle_cmd.js, website/scripts/ros/ros_route.js, website/scripts/ros/ros_system_status.js, website/thirdparty/jquery-plugins/jquery.msgPop.js
Update subscription to different topics to get data for : brake, steering_wheel, pinpoint status.
Fixed login/logout functionalities to allow them to start and stop backend ROS processes. 
Update the number of warning popup messages to display
Fixed display navigation menu upon engaged
Fixed route display after refreshing the screen
Added desktop icon for CARMA UI. Click on the desktop icon to allow it open google-chrome browser in app mode. 
https://github.com/usdot-fhwa-stol/carma-platform/issues/869
Integration testing in silver lexus
Integration testing in silver lexus vehicle
UI, javascritps
=> Integration/ui branch - CARMA Web UI integration testing bug fix

website/scripts/ros/ros_drivers_state.js
update logic to display pinpoint driver status
https://github.com/usdot-fhwa-stol/carma-platform/issues/869
JS error
Local UI testing
JS change
=> update pinpoint status

website/index.html, website/scripts/index.js, website/scripts/launchPlatform.php
update login logic to prevent redirecting pages if ROS connection is not up
Release branch integration testing issue
Vehicle integration testing
JS
=> update login logic

website/index.html, website/scripts/index.js
Follow up with the IP config 
release testing issue
Local integration testing
=> update carma config  IP

website/main.html, website/scripts/carma.config.js, website/scripts/carma.widgetfw.js, website/scripts/control.js, website/scripts/rosbridge.js, website/widgets/autoware/widget.css, website/widgets/autoware/widget.js, website/widgets/cruising/widget.css, website/widgets/cruising/widget.js
For the ACE Demo,
Fix at a minimum the widget view to showcase the crusing plugin widget with the speedometer that's currently missing due to CARMA Guidance using Autoware Plugin.
Remove the obsolete sidebar icons that are no longer needed for the ACE Demo such as the lat and lon plugin indicator, the ACC indicator, and others.
https://github.com/usdot-fhwa-stol/carma-platform/issues/916
ACE Demo
Local integration testing
In Vehicle Integration Testing
=> CARMAWebUi - Fix the Widget View and Side Bars Issues

website/scripts/launch.bash, website/scripts/launchPlatform.php
remote launch check issue
https://github.com/usdot-fhwa-stol/carma-platform/issues/916
release testing
in-vehicle
=> Update Login script logic

.circleci/config.yml, hooks/build, website/index.html, website/samples/archive/scripts_old/carma.widgetfw.js, website/samples/archive/scripts_old/rosbridge.js, website/samples/archive/widgets_old/autoware/widget.css, website/samples/archive/widgets_old/autoware/widget.js, website/samples/archive/widgets_old/cruising/widget.css, website/samples/archive/widgets_old/cruising/widget.js, website/scripts/app/control.js, website/scripts/index.js
This PR is to merge the changes from release 3.4.3 back into the develop branch. According to @maefromm and @dan-du-car we can choose develop for all merge conflicts. Other change is that ci has been retargeted at develop
This is needed to keep the develop branch as a working version of our released master branch.
Has been tested as part of the Wanderer testing process.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md)
=> Feature/sync 3.4.3

.circleci/config.yml, .sonarqube/sonar-scanner.properties, Dockerfile, docker/build-image.sh, docker/get-component-version.sh, docker/get-image-name.sh, docker/get-repo-name.sh, docker/get-system-version.sh, docker/install.sh, docker/system_release.sh, install_scripts/carma_web_ui_setup.bash, website/samples/archive/index_bkp.html, website/samples/archive/main_bkp.html, website/samples/archive/scripts_old/googlemap.js, website/samples/archive/scripts_old/rosbridge.js, website/samples/bash_old/kill.bash, website/samples/bash_old/launch.bash, website/scripts/app/control.js, website/scripts/kill.bash, website/scripts/launch.bash, website/scripts/launchPlatform.php, website/styles/styles.css, website/utils/google_map/google_map.js
Updated all of the copyright dates in the repository.
Keeps the copyright up to date for legal reasons I suppose
Checked the changes and it only affect comments.
- [Y] I have added any new packages to the sonar-scanner.properties file
- [N] My change requires a change to the documentation.
- [Y] I have updated the documentation accordingly.
- [Y] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) 
- [Y] I have added tests to cover my changes.
- [Y] All new and existing tests passed.
=> updated copyright text

.circleci/config.yml, website/scripts/app/global_variables.js, website/scripts/app/subscribeROSServicesOnLoad.js, website/scripts/ros/ros_route.js, website/utils/modals/disengage_confirmation/disengage_confirmation.js
Allow users to reselect the same route on the UI after getting a LEFT ROUTE event.
https://github.com/usdot-fhwa-stol/carma-platform/issues/1057
release/vanden-plas
Local integration testing
will be tested in vehicle
=> Cannot restart same route after getting LEFT ROUTE event

website/scripts/ros/ros_event_info.js
UI for road weather. event reason type change from uint8 to string
N/A
N/A
=> UI for road weather

website/scripts/ros/ros_system_alert.js
Refer to usdot-fhwa-stol/carma-platform#918
Refer to usdot-fhwa-stol/carma-platform#918
https://github.com/usdot-fhwa-stol/carma-platform/issues/918
https://github.com/usdot-fhwa-stol/carma-platform/issues/918
DEVELOP branch after 3.3.0
=> Fix CARMAWebUi - Update Fatal and Shutdown Response on the UI

website/scripts/app/global_variables.js
Lane change status topic mismatch
Traffic Incident use case
Vehicle
=> Lane change status topic mismatch

website/scripts/app/global_variables.js
fix topic mismatch
Traffic Incident
=> Topic mismatch for lane change status

website/scripts/app/subscribeROSServicesOnLoad.js, website/scripts/ros/ros_event_info.js
Event info topics are not called
Zephry testing
Tested in vehicle
=> Web UI does not provide a notification when the vehicle has left the route, and system can be re-engaged when not on the route

website/scripts/app/global_variables.js, website/scripts/ros/ros_system_status.js, website/utils/google_map/google_map.js
Added polygon to map to indicate where the TCR bounding box land on the google map
N/A
Zephyr release testing
Local VM
=> update map with polygon for TCR

website/scripts/ros/ros_platooning_info.js
Fix actual gap display
Fix host vehicle position display
N/A
=> Platoon info

.circleci/config.yml, website/scripts/app/global_variables.js, website/scripts/ros/ros_platooning_info.js, website/scripts/ros/ros_system_status.js, website/utils/google_map/google_map.js
This PR is to Sync develop back up with release 3.6.0
=> Sync develop with 3 6

.circleci/config.yml, docker/build-image.sh
This PR updates the build tags for the docker image build for noetic
Get fully working docker noetic builds
Local build testing with ./build-image.sh -d
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md)
=> Update tags for noetic develop

Dockerfile, docker/install.sh
This PR introduces a modified `Dockerfile` and `docker/install.sh` script that targets the arm64v8 architecture. The `carma-web-ui` container image is normally built for the x86 architecture, which is incompatible with the platforms used on the C1T vehicles (NVIDIA Jetsons).
Fixes #98 
These changes allow the `carma-web-ui` container image to be built and deployed to the C1T vehicles, which helps in porting CARMA to the F1/10 platform (the base for C1T).
Modified Docker container image has been built successfully on an NVIDIA Jetson TX2.
=> Modify Docker files to support arm64 platform

website/scripts/app/global_variables.js, website/scripts/ros/ros_lane_change.js, website/scripts/ros/ros_platooning_info.js, website/utils/platooning_info/platooning_info.js
update UI lane change indicator topic and message
update actual gap / desire gap decimal places to 1
https://github.com/usdot-fhwa-stol/carma-platform/issues/1338
Release testing
will be tested in vehicle
=> Web-UI: fix lane change topic mismatch and gap decimal places

Dockerfile, docker/install.sh
This PR updates the `carma.config.js` symlink in the `docker/install.sh` file. The previous symlink targeted `scripts/carma.config.js`, but the CARMA Web UI now looks for `scripts/app/carma.config.js`. This prevented the `carma.config.js` file in a `carma-config` container from properly overwriting the `carma.config.js` stub.
Fixes #103 for the `noetic-f1tenth/develop` branch.
The CARMA Web UI does not look for a `carma.config.js` file in the `scripts/` directory (which is where the symlink is targeted). Instead, it looks in the `scripts/apps` directory. This meant the vehicle-specific `carma.config.js` file was not properly overwriting the `carma.config.js` stub. 
A `carma-web-ui` container with the proposed changes was built and integrated with a `carma-config` container. The CARMA Web …
=> Update symlink for carma.config.js file

website/scripts/app/global_variables.js, website/scripts/ros/ros_traffic_signal.js
Update traffic signal message type and topic:
traffic_signal_info ->"/message/incoming_j2735_spat"
cav_msgs/TrafficSignalInfoList ->"j2735_msgs/SPAT"
Workzone use case
Local integration testing
JS
=> Update traffic signal message type and topic

website/scripts/ros/ros_traffic_signal.js
=> Fix signal flicker issue

website/scripts/ros/ros_event_info.js
Update the geofence reason to "SIG_WZ" for workzone use case.
Update logic to display the correct icons
Update display label for workzone
N/A
Workzone use case
=> Update geofence reason for workzone

docker/install.sh
This PR updates the `carma.config.js` symlink in the `docker/install.sh` file. The previous symlink targeted `scripts/carma.config.js`, but the CARMA Web UI now looks for `scripts/app/carma.config.js`. This prevented the `carma.config.js` file in a `carma-config` container from properly overwriting the `carma.config.js` stub.
Fixes #103 for the `develop` branch.
The CARMA Web UI does not look for a `carma.config.js` file in the `scripts/` directory (which is where the symlink is targeted). Instead, it looks in the `scripts/apps` directory. This meant the vehicle-specific `carma.config.js` file was not properly overwriting the `carma.config.js` stub. 
A `carma-web-ui` container with the proposed changes was built and integrated with a `carma-config` container. The symlink used the …
=> Update symlink for carma.config.js file (develop)

website/scripts/ros/ros_traffic_signal.js
Update logic to process min_end_time from spat message
https://github.com/usdot-fhwa-stol/carma-platform/issues/1421
Workzone use case
N/A
=> Update logic to process min_end_time from spat message

website/main.html, website/scripts/app/control.js, website/scripts/app/global_variables.js, website/scripts/app/subscribeROSServicesOnLoad.js, website/scripts/ros/ros_UIInstructions.js
CARMA Web UI when a new route is received for CARMA Freight
CARMA Web UI sees the above message on the /ui/ui_instructions topic and displays a popup window for the user. Based on the example message listed above:a.This popup window would include the specified ‘msg’b.Selecting the ‘YES’ button would call /guidance/set_guidance_active with ‘True’. The popup should disappear and the Web UI should switch to the display used when the system is engaged.c.Selecting the ‘NO’ button or the ‘X’ button would call /guidance/set_guidance_active with ‘False’. The popup should disappear.
N/A
carma-freight
=> UI_Instruction : when a new route is received and require UI action

.circleci/config.yml
Sync develop with release a1 (3.8.0)
=> Sync develop with release a1 (3.8.0)

website/utils/modals/system_alert/system_alert.js
Update route event popup text to "Start A New Route"
N/A
carma freight testing
=> Update route event popup text to "Start A New Route"

.circleci/config.yml
This PR syncs the 3.10.0 release back into develop with Docker files points to develop.
=> Sync 3.10 with develop

.circleci/config.yml
Merge PR to formalize release of release/hudson into master as part of CARMA release process for carma-system-4.1.0. 
PR created automatically via CARMA release tool and Github CLI
This PR brings the tested and reviewed contents of the release/hudson release/candidate into master for final release preparation
This release branch (minus final version number changes) has been tested through the CARMA verification test plan.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md)
=> Merge release to master for release carma-system-4.1.0

website/scripts/app/global_variables.js
This PR updates the required_plugins parameter to point at the ros2 version instead of ros1 version following the ros2 updates. 
https://github.com/usdot-fhwa-stol/carma-platform/issues/1896
Working ROS2 UI
=> Correct parameter name

docker/install.sh, hooks/build
=> Fix docker hub prebuild hook and update install script

website/scripts/app/subscribeROSServicesOnLoad.js, website/scripts/ros/ros_guidance.js, website/scripts/ros/ros_route.js, website/scripts/ros/ros_system_status.js
When the WFD telematic bridge is connected to carma series software running on the spectra computer, the carma-web-ui on the computer does not allow users to select a route.
https://github.com/usdot-fhwa-stol/cda-telematics/issues/74
WFD data collection
White Fusion
=> Web UI: SetRoute to active service call does not work

website/scripts/app/subscribeROSServicesOnLoad.js
The function to subscribe route event is commented out due to some messages were no longer defined in ROS2. This function is also subscribing to the route event topic. Uncomment this function to allow UI to subscribe to route event topic.
[carma-platform issue #2069](https://github.com/usdot-fhwa-stol/carma-platform/issues/2069)
Freight ERV testing
Tested on the White Truck; verified that the /ui/rosbridge_websocket carma-platform node was subscribed to /guidance/route_event, and that a "route completed" notification was displayed when the truck stopped at the end of its route.
=> Fix route event

Dockerfile
=> Dockerfile: bump base image to Debian Buster

.github/workflows/issue-notification.yml, Dockerfile, website/scripts/ros/ros_route.js, website/utils/google_map/google_map.js
This PR includes the Stingray release updates and merges the release/stingray branch into master as part of the release process. After the merge, master branch tagged  and deployed with new version carma-system-4.11.0.
The current version (4.11.0) and release history of the CARMA software platform: [CARMA Release Notes](https://github.com/usdot-fhwa-stol/carma-platform/blob/master/docs/Release_notes.md)
[CDAD-179](https://usdot-carma.atlassian.net/browse/CDAD-179)
[CDAD-179]: https://usdot-carma.atlassian.net/browse/CDAD-179?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Merge release/tempest(4.11.0) branch into master
